<?php
if ( ! defined('ABSPATH') ) exit;

class RTOFLOW_CitySeeder {

    public function run(): void {
        global $wpdb;

        // Add slug + rto_code columns if missing
        $cols = $wpdb->get_col("SHOW COLUMNS FROM {$wpdb->prefix}rto_cities");
        if ( ! in_array('slug', $cols) ) {
            $wpdb->query("ALTER TABLE {$wpdb->prefix}rto_cities ADD COLUMN slug VARCHAR(200) NULL, ADD COLUMN rto_code VARCHAR(30) NULL, ADD COLUMN rto_detail VARCHAR(200) NULL");
            $wpdb->query("ALTER TABLE {$wpdb->prefix}rto_cities ADD INDEX idx_slug (slug)");
        }

        // 300 priority cities
        $cities = [
        ['Faridabad','Haryana','faridabad','HR31 – Far','HR31 – Faridabad (Faridabad district).'],
        ['Ghaziabad','Uttar Pradesh','ghaziabad','UP14 – Gha','UP14 – Ghaziabad (Ghaziabad district).'],
        ['Mumbai','Maharashtra','mumbai','MH01 – Mum','MH01 – Mumbai (South Mumbai).'],
        ['Pune','Maharashtra','pune','MH12 – Pun','MH12 – Pune (Pune district).'],
        ['Nashik','Maharashtra','nashik','MH15 – Nas','MH15 – Nashik (Nashik district).'],
        ['Nagpur','Maharashtra','nagpur','MH31 – Nag','MH31 – Nagpur (Nagpur district).'],
        ['Thane','Maharashtra','thane','MH04 – Tha','MH04 – Thane (Thane district).'],
        ['Mangaluru','Karnataka','mangaluru','KA19 – Man','KA19 – Mangaluru (Dakshina Kannada district).'],
        ['Hyderabad','Telangana (TS / TG / district codes)','hyderabad','TS08 – Hyd','TS08 – Hyderabad (Hyderabad central).'],
        ['Chennai','Tamil Nadu','chennai','TN01 – Che','TN01 – Chennai (Central) (Chennai).'],
        ['Coimbatore','Tamil Nadu','coimbatore','TN43 – Coi','TN43 – Coimbatore (Central) (Coimbatore).'],
        ['Madurai','Tamil Nadu','madurai','TN36 – Mad','TN36 – Madurai (Madurai Central) (Madurai).'],
        ['Salem','Tamil Nadu','salem','TN28 – Sal','TN28 – Salem (Salem).'],
        ['Kolkata','West Bengal','kolkata','WB01 – Kol','WB01 – Kolkata (Beltala / Kolkata central).'],
        ['Howrah','West Bengal','howrah','WB12 – How','WB12 – Howrah (Howrah).'],
        ['Ahmedabad','Gujarat','ahmedabad','GJ01 – Ahm','GJ01 – Ahmedabad (Ahmedabad district).'],
        ['Surat','Gujarat','surat','GJ05 – Sur','GJ05 – Surat (Surat district).'],
        ['Vadodara','Gujarat','vadodara','GJ06 – Vad','GJ06 – Vadodara (Vadodara district).'],
        ['Rajkot','Gujarat','rajkot','GJ03 – Raj','GJ03 – Rajkot (Rajkot district).'],
        ['Jaipur','Rajasthan','jaipur','RJ14 – Jai','RJ14 – Jaipur (Jaipur district).'],
        ['Jodhpur','Rajasthan','jodhpur','RJ19 – Jod','RJ19 – Jodhpur (Jodhpur district).'],
        ['Kota','Rajasthan','kota','RJ21 – Kot','RJ21 – Kota (Kota district).'],
        ['Udaipur','Himachal','udaipur','HP43 – Uda','HP43 – Udaipur (Lahaul & Spiti district).'],
        ['Udaipur','Rajasthan','udaipur','RJ28 – Uda','RJ28 – Udaipur (Udaipur district).'],
        ['Lucknow','Uttar Pradesh','lucknow','UP32 – Luc','UP32 – Lucknow (Lucknow district).'],
        ['Agra','Uttar Pradesh','agra','UP77 – Agr','UP77 – Agra (Agra district).'],
        ['Varanasi','Uttar Pradesh','varanasi','UP65 – Var','UP65 – Varanasi (Varanasi district).'],
        ['Meerut','Uttar Pradesh','meerut','UP15 – Mee','UP15 – Meerut (Meerut district).'],
        ['Chandigarh','Chandigarh','chandigarh','CH01 – Cha','CH01 – Chandigarh (Central Office / Sector 17, Chandigarh).'],
        ['Amritsar','Punjab','amritsar','PB02 – Amr','PB02 – Amritsar (Amritsar district).'],
        ['Ludhiana','Punjab','ludhiana','PB10 – Lud','PB10 – Ludhiana (Ludhiana district).'],
        ['Patna','Bihar','patna','BR01 – Pat','BR01 – Patna (Patna district).'],
        ['Ranchi','Jharkhand','ranchi','JH01 – Ran','JH01 – Ranchi (Ranchi district).'],
        ['Bhopal','Madhya Pradesh','bhopal','MP04 – Bho','MP04 – Bhopal (Bhopal district).'],
        ['Indore','Madhya Pradesh','indore','MP09 – Ind','MP09 – Indore (Indore district).'],
        ['Jabalpur','Madhya Pradesh','jabalpur','MP20 – Jab','MP20 – Jabalpur (Jabalpur district).'],
        ['Raipur','Chhattisgarh','raipur','CG04 – Rai','CG04 – Raipur (Raipur district)'],
        ['Bhubaneswar','Odisha','bhubaneswar','OD02 – Bhu','OD02 – Bhubaneswar (Khordha district / Bhubaneswar).'],
        ['Cuttack','Odisha','cuttack','OD05 – Cut','OD05 – Cuttack (Cuttack district).'],
        ['Guwahati','Assam','guwahati','AS01 – Guw','AS01 – Guwahati (Kamrup Metropolitan district)'],
        ['Thiruvananthapuram','Kerala','thiruvananthapuram','KL01 – Thi','KL01 – Thiruvananthapuram (Thiruvananthapuram district).'],
        ['Kozhikode','Kerala','kozhikode','KL11 – Koz','KL11 – Kozhikode (Kozhikode district).'],
        ['Visakhapatnam','Andhra Pradesh','visakhapatnam','AP31 – Vis','AP31 – Visakhapatnam (Visakhapatnam district).'],
        ['Vijayawada','Andhra Pradesh','vijayawada','AP17 – Vij','AP17 – Vijayawada (NTR district).'],
        ['Dehradun','Uttrakhand','dehradun','UK07 – Deh','UK07 – Dehradun (Dehradun).'],
        ['Haridwar','Uttrakhand','haridwar','UK08 – Har','UK08 – Haridwar (Haridwar).'],
        ['Shimla','Himachal','shimla','HP07 – Shi','HP07 – Shimla (alternate).'],
        ['Jammu','Jammu and Kashmir (JK series)','jammu','JK02 – Jam','JK02 – Jammu (Jammu district).'],
        ['Srinagar','Jammu and Kashmir (JK series)','srinagar','JK01 – Sri','JK01 – Srinagar (Srinagar district).'],
        ['Kohima','Nagaland','kohima','NL01 – Koh','NL01 – Kohima (Kohima district).'],
        ['Agartala','Tripura (TR series)','agartala','TR01 – Aga','TR01 – Agartala (Agartala Central).'],
        ['Panaji','Goa','panaji','GA01 – Pan','GA01 – Panaji (North Goa district).'],
        ['Port Blair','Andaman and Nicobar Islands','port-blair','AN01 – Por','AN01 – Port Blair (South Andaman district).'],
        ['Car Nicobar','Andaman and Nicobar Islands','car-nicobar','AN02 – Car','AN02 – Car Nicobar (Nicobar district).'],
        ['Diglipur','Andaman and Nicobar Islands','diglipur','AN05 – Dig','AN05 – Diglipur (North & Middle Andaman district).'],
        ['Mayabunder','Andaman and Nicobar Islands','mayabunder','AN04 – May','AN04 – Mayabunder (North & Middle Andaman district).'],
        ['Nancowry','Andaman and Nicobar Islands','nancowry','AN03 – Nan','AN03 – Nancowry (Nicobar district).'],
        ['Adoni','Andhra Pradesh','adoni','AP21 – Ado','AP21 – Adoni (Kurnool district).'],
        ['Amalapuram','Andhra Pradesh','amalapuram','AP06 – Ama','AP06 – Amalapuram (Konaseema district).'],
        ['Anakapalli','Andhra Pradesh','anakapalli','AP33 – Ana','AP33 – Anakapalli (Anakapalli district).'],
        ['Anantapuramu','Andhra Pradesh','anantapuramu','AP02 – Ana','AP02 – Anantapuramu (Anantapuramu district).'],
        ['Andhra Pradesh','Andhra Pradesh','andhra-pradesh','AP39 – And','AP39 – Andhra Pradesh (State-wide series for new registrations).'],
        ['Bhimavaram','Andhra Pradesh','bhimavaram','AP37 – Bhi','AP37 – Bhimavaram (West Godavari district).'],
        ['Chirala','Andhra Pradesh','chirala','AP27 – Chi','AP27 – Chirala (Prakasam district).'],
        ['Chittoor','Andhra Pradesh','chittoor','AP03 – Chi','AP03 – Chittoor (Chittoor district).'],
        ['Eluru','Andhra Pradesh','eluru','AP38 – Elu','AP38 – Eluru (Eluru district).'],
        ['Gajuwaka','Andhra Pradesh','gajuwaka','AP32 – Gaj','AP32 – Gajuwaka (Visakhapatnam district).'],
        ['Gudivada','Andhra Pradesh','gudivada','AP16 – Gud','AP16 – Gudivada (Krishna district).'],
        ['Guntur','Andhra Pradesh','guntur','AP08 – Gun','AP08 – Guntur (Guntur district).'],
        ['Kakinada','Andhra Pradesh','kakinada','AP05 – Kak','AP05 – Kakinada (East Godavari district).'],
        ['Narasaraopet','Andhra Pradesh','narasaraopet','AP07 – Nar','AP07 – Narasaraopet (Palnadu district).'],
        ['Nellore','Andhra Pradesh','nellore','AP26 – Nel','AP26 – Nellore (SPSR Nellore district).'],
        ['Paderu','Andhra Pradesh','paderu','AP34 – Pad','AP34 – Paderu (Alluri Sitharama Raju district).'],
        ['Srikakulam','Andhra Pradesh','srikakulam','AP30 – Sri','AP30 – Srikakulam (Srikakulam district).'],
        ['Vizianagaram','Andhra Pradesh','vizianagaram','AP35 – Viz','AP35 – Vizianagaram (Vizianagaram district).'],
        ['YSR Kadapa','Andhra Pradesh','ysr-kadapa','AP04 – YSR','AP04 – YSR Kadapa (YSR Kadapa district).'],
        ['Aalo','Arunachal Pradesh','aalo','AR08 – Aal','AR08 – Aalo (West Siang district).'],
        ['Anini','Arunachal Pradesh','anini','AR10 – Ani','AR10 – Anini (Dibang Valley district).'],
        ['Basar','Arunachal Pradesh','basar','AR25 – Bas','AR25 – Basar (Lepa Rada district).'],
        ['Bomdila','Arunachal Pradesh','bomdila','AR04 – Bom','AR04 – Bomdila (West Kameng district).'],
        ['Changlang','Arunachal Pradesh','changlang','AR12 – Cha','AR12 – Changlang (Changlang district).'],
        ['Daporijo','Arunachal Pradesh','daporijo','AR07 – Dap','AR07 – Daporijo (Upper Subansiri district).'],
        ['Hawai','Arunachal Pradesh','hawai','AR17 – Haw','AR17 – Hawai (Anjaw district).'],
        ['Itanagar','Arunachal Pradesh','itanagar','AR01 – Ita','AR01 – Itanagar (Papum Pare district).'],
        ['Khonsa','Arunachal Pradesh','khonsa','AR13 – Kho','AR13 – Khonsa (Tirap district).'],
        ['Koloriang','Arunachal Pradesh','koloriang','AR15 – Kol','AR15 – Koloriang (Kurung Kumey district).'],
        ['Lemmi','Arunachal Pradesh','lemmi','AR24 – Lem','AR24 – Lemmi (Pakke-Kessang district).'],
        ['Likabali','Arunachal Pradesh','likabali','AR22 – Lik','AR22 – Likabali (Lower Siang district).'],
        ['Longding','Arunachal Pradesh','longding','AR18 – Lon','AR18 – Longding (Longding district).'],
        ['Naharlagun','Arunachal Pradesh','naharlagun','AR02 – Nah','AR02 – Naharlagun (Papum Pare district).'],
        ['Namsai','Arunachal Pradesh','namsai','AR20 – Nam','AR20 – Namsai (Namsai district).'],
        ['Palin','Arunachal Pradesh','palin','AR19 – Pal','AR19 – Palin (Kra Daadi district).'],
        ['Pangin','Arunachal Pradesh','pangin','AR21 – Pan','AR21 – Pangin (Siang district).'],
        ['Pasighat','Arunachal Pradesh','pasighat','AR09 – Pas','AR09 – Pasighat (East Siang district).'],
        ['Raga','Arunachal Pradesh','raga','AR23 – Rag','AR23 – Raga (Kamle district).'],
        ['Roing','Arunachal Pradesh','roing','AR16 – Roi','AR16 – Roing (Lower Dibang Valley district).'],
        ['Seppa','Arunachal Pradesh','seppa','AR05 – Sep','AR05 – Seppa (East Kameng district).'],
        ['Tawang','Arunachal Pradesh','tawang','AR03 – Taw','AR03 – Tawang (Tawang district).'],
        ['Tezu','Arunachal Pradesh','tezu','AR11 – Tez','AR11 – Tezu (Lohit district).'],
        ['Yingkiong','Arunachal Pradesh','yingkiong','AR14 – Yin','AR14 – Yingkiong (Upper Siang district).'],
        ['Ziro','Arunachal Pradesh','ziro','AR06 – Zir','AR06 – Ziro (Lower Subansiri district).'],
        ['(also for Assam Police Vehicles)','Assam','also-for-assam-police-vehicles','AS31 – (al','AS31 – (also for Assam Police Vehicles)'],
        ['Assam Police Vehicles','Assam','assam-police-vehicles','AS30 – Ass','AS30 – Assam Police Vehicles (State-wide/Police registration)'],
        ['Baksa','Assam','baksa','AS28 – Bak','AS28 – Baksa (Baksa district)'],
        ['Barpeta','Assam','barpeta','AS15 – Bar','AS15 – Barpeta (Barpeta district)'],
        ['Bongaigaon','Assam','bongaigaon','AS19 – Bon','AS19 – Bongaigaon (Bongaigaon district)'],
        ['Charaideo','Assam','charaideo','AS33 – Cha','AS33 – Charaideo (Charaideo district)'],
        ['Chirang','Assam','chirang','AS26 – Chi','AS26 – Chirang (Chirang district)'],
        ['Darrang','Assam','darrang','AS13 – Dar','AS13 – Darrang (Darrang district)'],
        ['Dhemaji','Assam','dhemaji','AS22 – Dhe','AS22 – Dhemaji (Dhemaji district)'],
        ['Dhubri','Assam','dhubri','AS17 – Dhu','AS17 – Dhubri (Dhubri district)'],
        ['Dibrugarh','Assam','dibrugarh','AS06 – Dib','AS06 – Dibrugarh (Dibrugarh district)'],
        ['Dima Hasao','Assam','dima-hasao','AS08 – Dim','AS08 – Dima Hasao (Dima Hasao district)'],
        ['Goalpara','Assam','goalpara','AS18 – Goa','AS18 – Goalpara (Goalpara district)'],
        ['Golaghat','Assam','golaghat','AS05 – Gol','AS05 – Golaghat (Golaghat district)'],
        ['Hailakandi','Assam','hailakandi','AS24 – Hai','AS24 – Hailakandi (Hailakandi district)'],
        ['Jorhat','Assam','jorhat','AS03 – Jor','AS03 – Jorhat (Jorhat district)'],
        ['Kamrup Rural','Assam','kamrup-rural','AS25 – Kam','AS25 – Kamrup Rural (Kamrup Rural district)'],
        ['Karbi Anglong','Assam','karbi-anglong','AS09 – Kar','AS09 – Karbi Anglong (Karbi Anglong district)'],
        ['Karimganj','Assam','karimganj','AS10 – Kar','AS10 – Karimganj (Karimganj district)'],
        ['Kokrajhar','Assam','kokrajhar','AS16 – Kok','AS16 – Kokrajhar (Kokrajhar district)'],
        ['Lakhimpur','Assam','lakhimpur','AS07 – Lak','AS07 – Lakhimpur (Lakhimpur district)'],
        ['Majuli','Assam','majuli','AS29 – Maj','AS29 – Majuli (Majuli district)'],
        ['Morigaon','Assam','morigaon','AS21 – Mor','AS21 – Morigaon (Morigaon district)'],
        ['Nagaon','Assam','nagaon','AS02 – Nag','AS02 – Nagaon (Nagaon district)'],
        ['Nalbari','Assam','nalbari','AS14 – Nal','AS14 – Nalbari (Nalbari district)'],
        ['Sibsagar','Assam','sibsagar','AS04 – Sib','AS04 – Sibsagar (Sivasagar district)'],
        ['Silchar','Assam','silchar','AS11 – Sil','AS11 – Silchar (Cachar district)'],
        ['South Salmara-Mankachar','Assam','south-salmara-mankachar','AS34 – Sou','AS34 – South Salmara-Mankachar (South Salmara-Mankachar district)'],
        ['Tezpur','Assam','tezpur','AS12 – Tez','AS12 – Tezpur (Sonitpur district)'],
        ['Tinsukia','Assam','tinsukia','AS23 – Tin','AS23 – Tinsukia (Tinsukia district)'],
        ['Udalguri','Assam','udalguri','AS27 – Uda','AS27 – Udalguri (Udalguri district)'],
        ['Araria','Bihar','araria','BR38 – Ara','BR38 – Araria (Araria district).'],
        ['Arrah','Bihar','arrah','BR03 – Arr','BR03 – Arrah (Bhojpur district).'],
        ['Arwal','Bihar','arwal','BR56 – Arw','BR56 – Arwal (Arwal district).'],
        ['Aurangabad','Bihar','aurangabad','BR26 – Aur','BR26 – Aurangabad (Aurangabad district).'],
        ['Banka','Bihar','banka','BR51 – Ban','BR51 – Banka (Banka district).'],
        ['Begusarai','Bihar','begusarai','BR09 – Beg','BR09 – Begusarai (Begusarai district).'],
        ['Bettiah','Bihar','bettiah','BR22 – Bet','BR22 – Bettiah (West Champaran district).'],
        ['Bhabua / Kaimur','Bihar','bhabua-kaimur','BR45 – Bha','BR45 – Bhabua / Kaimur (Kaimur district).'],
        ['Bhagalpur','Bihar','bhagalpur','BR10 – Bha','BR10 – Bhagalpur (Bhagalpur district).'],
        ['Bihar Sharif','Bihar','bihar-sharif','BR21 – Bih','BR21 – Bihar Sharif (Nalanda district).'],
        ['Buxar','Bihar','buxar','BR44 – Bux','BR44 – Buxar (Buxar district).'],
        ['Chhapra','Bihar','chhapra','BR04 – Chh','BR04 – Chhapra (Saran district).'],
        ['Darbhanga','Bihar','darbhanga','BR07 – Dar','BR07 – Darbhanga (Darbhanga district).'],
        ['Dehri / Rohtas','Bihar','dehri-rohtas','BR24 – Deh','BR24 – Dehri / Rohtas (Rohtas district).'],
        ['Gaya','Bihar','gaya','BR02 – Gay','BR02 – Gaya (Gaya district).'],
        ['Gopalganj','Bihar','gopalganj','BR28 – Gop','BR28 – Gopalganj (Gopalganj district).'],
        ['Hajipur','Bihar','hajipur','BR31 – Haj','BR31 – Hajipur (Vaishali district).'],
        ['Jamui','Bihar','jamui','BR46 – Jam','BR46 – Jamui (Jamui district).'],
        ['Jehanabad','Bihar','jehanabad','BR25 – Jeh','BR25 – Jehanabad (Jehanabad district).'],
        ['Katihar','Bihar','katihar','BR39 – Kat','BR39 – Katihar (Katihar district).'],
        ['Khagaria','Bihar','khagaria','BR34 – Kha','BR34 – Khagaria (Khagaria district).'],
        ['Kishanganj','Bihar','kishanganj','BR37 – Kis','BR37 – Kishanganj (Kishanganj district).'],
        ['Lakhisarai','Bihar','lakhisarai','BR53 – Lak','BR53 – Lakhisarai (Lakhisarai district).'],
        ['Madhepura','Bihar','madhepura','BR43 – Mad','BR43 – Madhepura (Madhepura district).'],
        ['Madhubani','Bihar','madhubani','BR32 – Mad','BR32 – Madhubani (Madhubani district).'],
        ['Motihari','Bihar','motihari','BR05 – Mot','BR05 – Motihari (East Champaran district).'],
        ['Munger','Bihar','munger','BR08 – Mun','BR08 – Munger (Munger district).'],
        ['Muzaffarpur','Bihar','muzaffarpur','BR06 – Muz','BR06 – Muzaffarpur (Muzaffarpur district).'],
        ['Nawada','Bihar','nawada','BR27 – Naw','BR27 – Nawada (Nawada district).'],
        ['Purnia','Bihar','purnia','BR11 – Pur','BR11 – Purnia (Purnia district).'],
        ['Rohtas','Bihar','rohtas','BR57 – Roh','BR57 – Rohtas (alternate/Dehri series, Rohtas district).'],
        ['Saharsa','Bihar','saharsa','BR19 – Sah','BR19 – Saharsa (Saharsa district).'],
        ['Samastipur','Bihar','samastipur','BR33 – Sam','BR33 – Samastipur (Samastipur district).'],
        ['Sheikhpura','Bihar','sheikhpura','BR52 – She','BR52 – Sheikhpura (Sheikhpura district).'],
        ['Sheohar','Bihar','sheohar','BR55 – She','BR55 – Sheohar (Sheohar district).'],
        ['Sitamarhi','Bihar','sitamarhi','BR30 – Sit','BR30 – Sitamarhi (Sitamarhi district).'],
        ['Siwan','Bihar','siwan','BR29 – Siw','BR29 – Siwan (Siwan district).'],
        ['Supaul','Bihar','supaul','BR50 – Sup','BR50 – Supaul (Supaul district).'],
        ['(State-wide for Government vehicles)','Chhattisgarh','state-wide-for-government-vehicles','CG02 – (St','CG02 – (State-wide for Government vehicles)'],
        ['(State-wide for Governor vehicles)','Chhattisgarh','state-wide-for-governor-vehicles','CG01 – (St','CG01 – (State-wide for Governor vehicles)'],
        ['(State-wide for Police vehicles)','Chhattisgarh','state-wide-for-police-vehicles','CG03 – (St','CG03 – (State-wide for Police vehicles)'],
        ['Ambikapur','Chhattisgarh','ambikapur','CG15 – Amb','CG15 – Ambikapur (Surguja district)'],
        ['Baikunthpur','Chhattisgarh','baikunthpur','CG16 – Bai','CG16 – Baikunthpur (Koriya district)'],
        ['Balod','Chhattisgarh','balod','CG24 – Bal','CG24 – Balod (Balod district)'],
        ['Baloda Bazar','Chhattisgarh','baloda-bazar','CG22 – Bal','CG22 – Baloda Bazar (Baloda Bazar district)'],
        ['Balrampur','Chhattisgarh','balrampur','CG30 – Bal','CG30 – Balrampur (Balrampur district)'],
        ['Bemetara','Chhattisgarh','bemetara','CG25 – Bem','CG25 – Bemetara (Bemetara district)'],
        ['Bijapur','Chhattisgarh','bijapur','CG20 – Bij','CG20 – Bijapur (Bijapur district)'],
        ['Bilaspur','Chhattisgarh','bilaspur','CG10 – Bil','CG10 – Bilaspur (Bilaspur district)'],
        ['Dantewada','Chhattisgarh','dantewada','CG18 – Dan','CG18 – Dantewada (Dantewada district)'],
        ['Dhamtari','Chhattisgarh','dhamtari','CG05 – Dha','CG05 – Dhamtari (Dhamtari district)'],
        ['Durg','Chhattisgarh','durg','CG07 – Dur','CG07 – Durg (Durg district)'],
        ['Gariaband','Chhattisgarh','gariaband','CG23 – Gar','CG23 – Gariaband (Gariaband district)'],
        ['Jagdalpur','Chhattisgarh','jagdalpur','CG17 – Jag','CG17 – Jagdalpur (Bastar district)'],
        ['Janjgir-Champa','Chhattisgarh','janjgir-champa','CG11 – Jan','CG11 – Janjgir-Champa (Janjgir-Champa district)'],
        ['Jashpur','Chhattisgarh','jashpur','CG14 – Jas','CG14 – Jashpur (Jashpur district)'],
        ['Kabirdham','Chhattisgarh','kabirdham','CG09 – Kab','CG09 – Kabirdham (Kabirdham district)'],
        ['Kanker','Chhattisgarh','kanker','CG19 – Kan','CG19 – Kanker (Kanker district)'],
        ['Kondagaon','Chhattisgarh','kondagaon','CG27 – Kon','CG27 – Kondagaon (Kondagaon district)'],
        ['Korba','Chhattisgarh','korba','CG12 – Kor','CG12 – Korba (Korba district)'],
        ['Mahasamund','Chhattisgarh','mahasamund','CG06 – Mah','CG06 – Mahasamund (Mahasamund district)'],
        ['Mungeli','Chhattisgarh','mungeli','CG28 – Mun','CG28 – Mungeli (Mungeli district)'],
        ['Narayanpur','Chhattisgarh','narayanpur','CG21 – Nar','CG21 – Narayanpur (Narayanpur district)'],
        ['Raigarh','Chhattisgarh','raigarh','CG13 – Rai','CG13 – Raigarh (Raigarh district)'],
        ['Rajnandgaon','Chhattisgarh','rajnandgaon','CG08 – Raj','CG08 – Rajnandgaon (Rajnandgaon district)'],
        ['Sukma','Chhattisgarh','sukma','CG26 – Suk','CG26 – Sukma (Sukma district)'],
        ['Surajpur','Chhattisgarh','surajpur','CG29 – Sur','CG29 – Surajpur (Surajpur district)'],
        ['Daman','Dadra and Nagar Haveli and Daman and Diu (DD / DN series)','daman','DD01 – Dam','DD01 – Daman (Daman district).'],
        ['Diu','Dadra and Nagar Haveli and Daman and Diu (DD / DN series)','diu','DD02 – Diu','DD02 – Diu (Diu district).'],
        ['Silvassa','Dadra and Nagar Haveli and Daman and Diu (DD / DN series)','silvassa','DN09 – Sil','DN09 – Silvassa (Dadra and Nagar Haveli district).'],
        ['Dwarka','Delhi','dwarka','DL09 – Dwa','DL09 – Dwarka, South West Delhi (Najafgarh, Palam, etc.)'],
        ['Janakpuri','Delhi','janakpuri','DL04 – Jan','DL04 – Janakpuri, West Delhi (Vikaspuri, Rajouri Garden, etc.)'],
        ['Loni Road','Delhi','loni-road','DL05 – Lon','DL05 – Loni Road, North East Delhi (Seelampur, Shahdara, etc.)'],
        ['Mall Road','Delhi','mall-road','DL01 – Mal','DL01 – Mall Road, North Delhi (Model Town, Civil Lines, etc.)'],
        ['Mayur Vihar','Delhi','mayur-vihar','DL07 – May','DL07 – Mayur Vihar, East Delhi (Preet Vihar, Patparganj, etc.)'],
        ['Raja Garden','Delhi','raja-garden','DL10 – Raj','DL10 – Raja Garden, West Delhi-II (Punjabi Bagh, Paschim Vihar, etc.)'],
        ['Rohini','Delhi','rohini','DL11 – Roh','DL11 – Rohini, North West Delhi-II (Rohini, Pitampura, Mangolpuri, etc.)'],
        ['Sarai Kale Khan','Delhi','sarai-kale-khan','DL06 – Sar','DL06 – Sarai Kale Khan, South East Delhi (Lajpat Nagar, Okhla, etc.)'],
        ['Sheikh Sarai','Delhi','sheikh-sarai','DL03 – She','DL03 – Sheikh Sarai, South Delhi (Saket, Mehrauli, etc.)'],
        ['Surajmal Vihar','Delhi','surajmal-vihar','DL13 – Sur','DL13 – Surajmal Vihar, East Delhi-II (Vivek Vihar, Anand Vihar, etc.)'],
        ['Tilak Marg','Delhi','tilak-marg','DL02 – Til','DL02 – Tilak Marg, Central Delhi (Connaught Place, Darya Ganj, etc.)'],
        ['Vasant Vihar','Delhi','vasant-vihar','DL12 – Vas','DL12 – Vasant Vihar, South Delhi-II (Vasant Kunj, Chanakyapuri, RK Puram, etc.)'],
        ['Wazirpur','Delhi','wazirpur','DL08 – Waz','DL08 – Wazirpur, North West Delhi (Ashok Vihar, Shalimar Bagh, etc.)'],
        ['Bicholim','Goa','bicholim','GA04 – Bic','GA04 – Bicholim (North Goa district).'],
        ['Canacona','Goa','canacona','GA10 – Can','GA10 – Canacona (South Goa district).'],
        ['Dharbandora','Goa','dharbandora','GA12 – Dha','GA12 – Dharbandora (South Goa district).'],
        ['Mapusa','Goa','mapusa','GA03 – Map','GA03 – Mapusa (North Goa district).'],
        ['Margao','Goa','margao','GA02 – Mar','GA02 – Margao (South Goa district).'],
        ['Pernem','Goa','pernem','GA11 – Per','GA11 – Pernem (North Goa district).'],
        ['Ponda','Goa','ponda','GA05 – Pon','GA05 – Ponda (Ponda district).'],
        ['Quepem','Goa','quepem','GA09 – Que','GA09 – Quepem (South Goa district).'],
        ['Vasco da Gama','Goa','vasco-da-gama','GA06 – Vas','GA06 – Vasco da Gama (Mormugao, South Goa district).'],
        ['Ahmedabad East','Gujarat','ahmedabad-east','GJ27 – Ahm','GJ27 – Ahmedabad East (Ahmedabad district).'],
        ['Amreli','Gujarat','amreli','GJ14 – Amr','GJ14 – Amreli (Amreli district).'],
        ['Anand','Gujarat','anand','GJ23 – Ana','GJ23 – Anand (Anand district).'],
        ['Bardoli','Gujarat','bardoli','GJ19 – Bar','GJ19 – Bardoli (Surat district).'],
        ['Bharuch','Gujarat','bharuch','GJ16 – Bha','GJ16 – Bharuch (Bharuch district).'],
        ['Bhavnagar','Gujarat','bhavnagar','GJ04 – Bha','GJ04 – Bhavnagar (Bhavnagar district).'],
        ['Bhuj','Gujarat','bhuj','GJ12 – Bhu','GJ12 – Bhuj (Kutch district).'],
        ['Dahod','Gujarat','dahod','GJ20 – Dah','GJ20 – Dahod (Dahod district).'],
        ['Gandhinagar','Gujarat','gandhinagar','GJ18 – Gan','GJ18 – Gandhinagar (Gandhinagar district).'],
        ['Godhra','Gujarat','godhra','GJ17 – God','GJ17 – Godhra (Panchmahal district).'],
        ['Himmatnagar','Gujarat','himmatnagar','GJ09 – Him','GJ09 – Himmatnagar (Sabarkantha district).'],
        ['Jamnagar','Gujarat','jamnagar','GJ10 – Jam','GJ10 – Jamnagar (Jamnagar district).'],
        ['Junagadh','Gujarat','junagadh','GJ11 – Jun','GJ11 – Junagadh (Junagadh district).'],
        ['Mehsana','Gujarat','mehsana','GJ02 – Meh','GJ02 – Mehsana (Mehsana district).'],
        ['Nadiad','Gujarat','nadiad','GJ07 – Nad','GJ07 – Nadiad (Kheda district).'],
        ['Navsari','Gujarat','navsari','GJ21 – Nav','GJ21 – Navsari (Navsari district).'],
        ['Palanpur','Gujarat','palanpur','GJ08 – Pal','GJ08 – Palanpur (Banaskantha district).'],
        ['Patan','Gujarat','patan','GJ24 – Pat','GJ24 – Patan (Patan district).'],
        ['Porbandar','Gujarat','porbandar','GJ25 – Por','GJ25 – Porbandar (Porbandar district).'],
        ['Rajpipla','Gujarat','rajpipla','GJ22 – Raj','GJ22 – Rajpipla (Narmada district).'],
        ['Surat East','Gujarat','surat-east','GJ28 – Sur','GJ28 – Surat East (Surat district).'],
        ['Surendranagar','Gujarat','surendranagar','GJ13 – Sur','GJ13 – Surendranagar (Surendranagar district).'],
        ['Vadodara East','Gujarat','vadodara-east','GJ29 – Vad','GJ29 – Vadodara East (Vadodara district).'],
        ['Valsad','Gujarat','valsad','GJ15 – Val','GJ15 – Valsad (Valsad district).'],
        ['Vyara','Gujarat','vyara','GJ26 – Vya','GJ26 – Vyara (Tapi district).'],
        ['Ambala','Haryana','ambala','HR01 – Amb','HR01 – Ambala (Ambala district).'],
        ['Bhiwani','Haryana','bhiwani','HR24 – Bhi','HR24 – Bhiwani (Bhiwani district).'],
        ['Fatehabad','Haryana','fatehabad','HR26 – Fat','HR26 – Fatehabad (Fatehabad district).'],
        ['Gurugram','Haryana','gurugram','HR33 – Gur','HR33 – Gurugram (Gurugram district).'],
        ['Haryana','Haryana','haryana','HR99 – Har','HR99 – Haryana (temporary registrations statewide).'],
        ['Hisar','Haryana','hisar','HR22 – His','HR22 – Hisar (Hisar district).'],
        ['Jagadhri','Haryana','jagadhri','HR02 – Jag','HR02 – Jagadhri (Yamunanagar district).'],
        ['Jhajjar','Haryana','jhajjar','HR14 – Jha','HR14 – Jhajjar (Jhajjar district).'],
        ['Karnal','Haryana','karnal','HR05 – Kar','HR05 – Karnal (Karnal district).'],
        ['Mahendragarh','Haryana','mahendragarh','HR34 – Mah','HR34 – Mahendragarh (Mahendragarh district).'],
        ['Meham','Haryana','meham','HR15 – Meh','HR15 – Meham (Rohtak district).'],
        ['Mewat','Haryana','mewat','HR96 – Mew','HR96 – Mewat (Nuh district).'],
        ['Naraingarh','Haryana','naraingarh','HR04 – Nar','HR04 – Naraingarh (Haryana).'],
        ['Narnaul','Haryana','narnaul','HR35 – Nar','HR35 – Narnaul (Mahendragarh district).'],
        ['Panchkula','Haryana','panchkula','HR03 – Pan','HR03 – Panchkula (Panchkula district).'],
        ['Panipat','Haryana','panipat','HR06 – Pan','HR06 – Panipat (Panipat district).'],
        ['Rewari','Haryana','rewari','HR36 – Rew','HR36 – Rewari (Rewari district).'],
        ['Rohtak','Haryana','rohtak','HR46 – Roh','HR46 – Rohtak (Rohtak district).'],
        ['Amb','Himachal','amb','HP19 – Amb','HP19 – Amb (Sirmaur district).'],
        ['Anni','Himachal','anni','HP35 – Ann','HP35 – Anni (Kullu district).'],
        ['Arki','Himachal','arki','HP11 – Ark','HP11 – Arki (Solan district).'],
        ['Baijnath','Himachal','baijnath','HP53 – Bai','HP53 – Baijnath (Kangra district).'],
        ['Barsar','Himachal','barsar','HP21 – Bar','HP21 – Barsar (Hamirpur district).'],
        ['Bilaspur','Himachal','bilaspur','HP24 – Bil','HP24 – Bilaspur (Bilaspur district).'],
        ['Chamba','Himachal','chamba','HP44 – Cha','HP44 – Chamba (Chamba district).'],
        ['Chaupal','Himachal','chaupal','HP08 – Cha','HP08 – Chaupal (Shimla district).'],
        ['Chowari','Himachal','chowari','HP57 – Cho','HP57 – Chowari (Una district).'],
        ['Dharamsala','Himachal','dharamsala','HP04 – Dha','HP04 – Dharamsala (Kangra district).'],
        ['Ghumarwin','Himachal','ghumarwin','HP23 – Ghu','HP23 – Ghumarwin (Bilaspur district).'],
        ['Gohar','Himachal','gohar','HP32 – Goh','HP32 – Gohar (Mandi district).'],
        ['Hamirpur','Himachal','hamirpur','HP22 – Ham','HP22 – Hamirpur (Hamirpur district).'],
        ['Jawali','Himachal','jawali','HP54 – Jaw','HP54 – Jawali (Kangra district).'],
        ['Jogindernagar','Himachal','jogindernagar','HP29 – Jog','HP29 – Jogindernagar (Mandi district).'],
        ['Kalpa','Himachal','kalpa','HP25 – Kal','HP25 – Kalpa (Kinnaur district).'],
        ['Kandaghat','Himachal','kandaghat','HP13 – Kan','HP13 – Kandaghat (Solan district).'],
        ['Karsog','Himachal','karsog','HP30 – Kar','HP30 – Karsog (Mandi district).'],
        ['Keylong','Himachal','keylong','HP42 – Key','HP42 – Keylong (Lahaul & Spiti district).'],
        ['Kullu','Himachal','kullu','HP41 – Kul','HP41 – Kullu (additional).'],
        ['Manali','Himachal','manali','HP58 – Man','HP58 – Manali (Kullu district).'],
        ['Mandi','Himachal','mandi','HP05 – Man','HP05 – Mandi (Mandi district).'],
        ['Nadaun','Himachal','nadaun','HP55 – Nad','HP55 – Nadaun (Hamirpur district).'],
        ['Nahan','Himachal','nahan','HP18 – Nah','HP18 – Nahan (Sirmaur district).'],
        ['Nalagarh','Himachal','nalagarh','HP12 – Nal','HP12 – Nalagarh (Solan district).'],
        ['Paonta Sahib','Himachal','paonta-sahib','HP17 – Pao','HP17 – Paonta Sahib (Sirmaur district).'],
        ['Parwanoo','Himachal','parwanoo','HP15 – Par','HP15 – Parwanoo (Solan district).'],
        ['Pooh','Himachal','pooh','HP27 – Poo','HP27 – Pooh (Kinnaur district).'],
        ['Rajgarh','Himachal','rajgarh','HP16 – Raj','HP16 – Rajgarh (Sirmaur district).'],
        ['Rampur','Himachal','rampur','HP06 – Ram','HP06 – Rampur (Shimla district).'],
        ['Rohru','Himachal','rohru','HP10 – Roh','HP10 – Rohru (Shimla district).'],
        ['Shimla Urban','Himachal','shimla-urban','HP01 – Shi','HP01 – Shimla Urban (Shimla district).'],
        ['Solan','Himachal','solan','HP14 – Sol','HP14 – Solan (Solan district).'],
        ];

        foreach ( $cities as [$city, $state_name, $slug, $rto_code, $detail] ) {
            // Get or create state
            $state_id = (int) $wpdb->get_var( $wpdb->prepare(
                "SELECT id FROM {$wpdb->prefix}rto_states WHERE name=%s", $state_name
            ));
            if ( ! $state_id ) continue;

            // Check if city already exists by slug
            $exists = $wpdb->get_var( $wpdb->prepare(
                "SELECT id FROM {$wpdb->prefix}rto_cities WHERE slug=%s", $slug
            ));

            if ( $exists ) {
                $wpdb->update( $wpdb->prefix.'rto_cities', [
                    'rto_code'   => $rto_code,
                    'rto_detail' => $detail,
                    'is_active'  => 1,
                ], ['id' => $exists] );
            } else {
                $wpdb->insert( $wpdb->prefix.'rto_cities', [
                    'name'       => $city,
                    'state_id'   => $state_id,
                    'slug'       => $slug,
                    'rto_code'   => $rto_code,
                    'rto_detail' => $detail,
                    'is_active'  => 1,
                ]);
            }
        }
    }
}
