<?php
if (!defined('ABSPATH')) exit;
/**
 * Complete RTO office data for all 36 Indian states/UTs
 * Sourced from FluentForm JSON: fluentform-export-forms-1-21-05-2026.json
 */
$rtos_by_state = [
 'Andhra Pradesh'=>['AP02 – Anantapuramu','AP03 – Chittoor','AP04 – YSR Kadapa','AP05 – Kakinada','AP06 – Amalapuram (Konaseema)','AP07 – Narasaraopet (Palnadu)','AP08 – Guntur','AP16 – Gudivada (Krishna)','AP17 – Vijayawada (NTR)','AP18 – Vijayawada-2','AP19 – Vijayawada-3','AP21 – Adoni (Kurnool)','AP26 – Nellore','AP27 – Chirala (Prakasam)','AP30 – Srikakulam','AP31 – Visakhapatnam','AP32 – Gajuwaka (Visakhapatnam)','AP33 – Anakapalli','AP34 – Paderu','AP35 – Vizianagaram','AP37 – Bhimavaram','AP38 – Eluru','AP39 – AP State-wide (new reg.)','AP40 – AP Special/Govt.'],
 'Arunachal Pradesh'=>['AR01 – Itanagar','AR02 – Naharlagun','AR03 – Tawang','AR04 – Bomdila','AR05 – Seppa','AR06 – Ziro','AR07 – Daporijo','AR08 – Aalo','AR09 – Pasighat','AR10 – Anini','AR11 – Tezu','AR12 – Changlang','AR13 – Khonsa','AR14 – Yingkiong','AR15 – Koloriang','AR16 – Roing','AR17 – Hawai','AR18 – Longding','AR19 – Palin','AR20 – Namsai','AR21 – Pangin','AR22 – Likabali','AR23 – Raga','AR24 – Lemmi','AR25 – Basar'],
 'Assam'=>['AS01 – Guwahati (Kamrup Metro.)','AS02 – Nagaon','AS03 – Jorhat','AS04 – Sibsagar','AS05 – Golaghat','AS06 – Dibrugarh','AS07 – Lakhimpur','AS08 – Dima Hasao','AS09 – Karbi Anglong','AS10 – Karimganj','AS11 – Silchar (Cachar)','AS12 – Tezpur (Sonitpur)','AS13 – Darrang','AS14 – Nalbari','AS15 – Barpeta','AS16 – Kokrajhar','AS17 – Dhubri','AS18 – Goalpara','AS19 – Bongaigaon','AS21 – Morigaon','AS22 – Dhemaji','AS23 – Tinsukia','AS24 – Hailakandi','AS25 – Kamrup Rural','AS26 – Chirang','AS27 – Udalguri','AS28 – Baksa','AS29 – Majuli','AS33 – Charaideo','AS34 – South Salmara-Mankachar'],
 'Bihar'=>['BR01 – Patna','BR02 – Gaya','BR03 – Arrah (Bhojpur)','BR04 – Chhapra (Saran)','BR05 – Motihari (East Champaran)','BR06 – Muzaffarpur','BR07 – Darbhanga','BR08 – Munger','BR09 – Begusarai','BR10 – Bhagalpur','BR11 – Purnia','BR19 – Saharsa','BR21 – Bihar Sharif (Nalanda)','BR22 – Bettiah (West Champaran)','BR24 – Dehri / Rohtas','BR25 – Jehanabad','BR26 – Aurangabad','BR27 – Nawada','BR28 – Gopalganj','BR29 – Siwan','BR30 – Sitamarhi','BR31 – Hajipur (Vaishali)','BR32 – Madhubani','BR33 – Samastipur','BR34 – Khagaria','BR37 – Kishanganj','BR38 – Araria','BR39 – Katihar','BR43 – Madhepura','BR44 – Buxar','BR45 – Bhabua / Kaimur','BR46 – Jamui','BR50 – Supaul','BR51 – Banka','BR52 – Sheikhpura','BR53 – Lakhisarai','BR55 – Sheohar','BR56 – Arwal'],
 'Chhattisgarh'=>['CG04 – Raipur','CG05 – Dhamtari','CG06 – Mahasamund','CG07 – Durg','CG08 – Rajnandgaon','CG09 – Kabirdham','CG10 – Bilaspur','CG11 – Janjgir-Champa','CG12 – Korba','CG13 – Raigarh','CG14 – Jashpur','CG15 – Ambikapur (Surguja)','CG16 – Baikunthpur (Koriya)','CG17 – Jagdalpur (Bastar)','CG18 – Dantewada','CG19 – Kanker','CG20 – Bijapur','CG21 – Narayanpur','CG22 – Baloda Bazar','CG23 – Gariaband','CG24 – Balod','CG25 – Bemetara','CG26 – Sukma','CG27 – Kondagaon','CG28 – Mungeli','CG29 – Surajpur','CG30 – Balrampur'],
 'Goa'=>['GA01 – Panaji (North Goa)','GA02 – Margao (South Goa)','GA03 – Mapusa','GA04 – Bicholim','GA05 – Ponda','GA06 – Vasco da Gama (Mormugao)','GA09 – Quepem','GA10 – Canacona','GA11 – Pernem','GA12 – Dharbandora'],
 'Gujarat'=>['GJ01 – Ahmedabad','GJ02 – Mehsana','GJ03 – Rajkot','GJ04 – Bhavnagar','GJ05 – Surat','GJ06 – Vadodara','GJ07 – Nadiad (Kheda)','GJ08 – Palanpur (Banaskantha)','GJ09 – Himmatnagar (Sabarkantha)','GJ10 – Jamnagar','GJ11 – Junagadh','GJ12 – Bhuj (Kutch)','GJ13 – Surendranagar','GJ14 – Amreli','GJ15 – Valsad','GJ16 – Bharuch','GJ17 – Godhra (Panchmahal)','GJ18 – Gandhinagar','GJ19 – Bardoli (Surat)','GJ20 – Dahod','GJ21 – Navsari','GJ22 – Rajpipla (Narmada)','GJ23 – Anand','GJ24 – Patan','GJ25 – Porbandar','GJ26 – Vyara (Tapi)','GJ27 – Ahmedabad East','GJ28 – Surat East','GJ29 – Vadodara East'],
 'Haryana'=>['HR01 – Ambala','HR02 – Jagadhri (Yamunanagar)','HR03 – Panchkula','HR05 – Karnal','HR06 – Panipat','HR14 – Jhajjar','HR22 – Hisar','HR24 – Bhiwani','HR26 – Fatehabad','HR31 – Faridabad','HR33 – Gurugram','HR34 – Mahendragarh','HR35 – Narnaul','HR36 – Rewari','HR46 – Rohtak','HR96 – Mewat (Nuh)','HR99 – Haryana Temp. Reg.'],
 'Himachal Pradesh'=>['HP01 – Shimla Urban','HP02 – Shimla Urban-2','HP03 – Shimla Urban-3','HP04 – Dharamsala (Kangra)','HP05 – Mandi','HP06 – Rampur','HP08 – Chaupal','HP09 – Theog','HP10 – Rohru','HP11 – Arki (Solan)','HP12 – Nalagarh','HP13 – Kandaghat','HP14 – Solan','HP15 – Parwanoo','HP16 – Rajgarh (Sirmaur)','HP17 – Paonta Sahib','HP18 – Nahan','HP20 – Una','HP22 – Hamirpur','HP24 – Bilaspur','HP25 – Kalpa (Kinnaur)','HP29 – Jogindernagar','HP30 – Karsog','HP31 – Sundernagar','HP32 – Gohar','HP35 – Anni (Kullu)','HP42 – Keylong (Lahaul & Spiti)','HP44 – Chamba','HP53 – Baijnath','HP54 – Jawali','HP58 – Manali','HP59 – Solan (Baddi)'],
 'Jharkhand'=>['JH01 – Ranchi','JH02 – Hazaribagh','JH03 – Daltonganj / Palamu','JH04 – Dumka','JH05 – Jamshedpur','JH06 – Chaibasa','JH07 – Gumla','JH08 – Lohardaga','JH09 – Bokaro Steel City','JH10 – Dhanbad','JH11 – Giridih','JH12 – Koderma','JH13 – Chatra','JH14 – Garhwa','JH15 – Deoghar','JH16 – Pakur','JH17 – Godda','JH18 – Sahibganj','JH19 – Latehar','JH20 – Simdega','JH21 – Jamtara','JH22 – Seraikela-Kharsawan','JH23 – Khunti','JH24 – Ramgarh'],
 'Karnataka'=>['KA01 – Bangalore Central','KA02 – Bangalore West','KA03 – Bangalore East','KA04 – Bangalore North','KA05 – Bangalore South','KA06 – Tumkur','KA07 – Kolar','KA08 – K.G.F. / Kolar Gold Fields','KA09 – Mysore West','KA10 – Chamarajanagar','KA11 – Mandya','KA12 – Madikeri (Kodagu)','KA13 – Hassan','KA14 – Shimoga','KA15 – Shimoga East','KA16 – Chitradurga','KA17 – Davanagere','KA18 – Chikkamagaluru','KA19 – Mangaluru','KA20 – Udupi','KA21 – Belagavi / Belgaum','KA22 – Bagalkot','KA23 – Vijayapura / Bijapur','KA24 – Dharwad','KA25 – Gadag','KA26 – Haveri','KA27 – Ballari / Bellary','KA28 – Koppal','KA29 – Raichur','KA30 – Yadgir','KA31 – Bidar','KA32 – Kalaburagi / Gulbarga','KA33 – Ramanagara','KA41 – Bangalore North East','KA50 – Mysuru East','KA51 – Bangalore Regional','KA52 – Bangalore North-West','KA53 – Bangalore South-East'],
 'Kerala'=>['KL01 – Thiruvananthapuram','KL02 – Kollam','KL03 – Pathanamthitta','KL04 – Alappuzha','KL05 – Kottayam','KL06 – Idukki','KL07 – Ernakulam','KL08 – Thrissur','KL09 – Palakkad','KL10 – Malappuram','KL11 – Kozhikode','KL12 – Wayanad','KL13 – Kannur','KL14 – Kasaragod','KL15 – KSRTC / Special','KL16 – Attingal (Sub RTO)','KL17 – Muvattupuzha (Sub RTO)','KL18 – Vadakara (Sub RTO)','KL19 – Parassala (Sub RTO)','KL20 – Neyyattinkara (Sub RTO)','KL23 – Karunagappalli (Sub RTO)','KL24 – Kottarakkara (Sub RTO)','KL25 – Punalur (Sub RTO)','KL26 – Adoor (Sub RTO)','KL27 – Thiruvalla (Sub RTO)','KL56 – Kozhikode (sub-regional)','KL58 – Thalassery (Kannur)','KL60 – Kanhangad (Kasaragod)','KL63 – Angamaly (Ernakulam)','KL64 – Chalakkudy (Thrissur)','KL65 – Tirurangadi (Malappuram)','KL72 – Mananthavady (Wayanad)','KL73 – Sulthan Bathery (Wayanad)','KL78 – Iritty (Kannur)','KL81 – Varkala (Thiruvananthapuram)','KL86 – Payyannur (Kannur)'],
 'Madhya Pradesh'=>['MP04 – Bhopal','MP05 – Hoshangabad / Narmadapuram','MP06 – Morena','MP07 – Gwalior','MP08 – Guna','MP09 – Indore','MP10 – Khargone','MP11 – Dhar','MP12 – Khandwa','MP13 – Ujjain','MP14 – Mandsaur','MP15 – Sagar','MP16 – Chhatarpur','MP17 – Rewa','MP18 – Shahdol','MP19 – Satna','MP20 – Jabalpur','MP21 – Narsinghpur','MP22 – Harda','MP23 – Betul','MP25 – Seoni','MP26 – Chhindwara','MP27 – Balaghat','MP28 – Sidhi','MP30 – Umaria','MP31 – Anuppur','MP32 – Ashoknagar','MP33 – Burhanpur','MP34 – Alirajpur','MP35 – Agar Malwa','MP36 – Damoh','MP37 – Raisen','MP38 – Shivpuri','MP39 – Tikamgarh','MP40 – Vidisha','MP42 – Sheopur','MP44 – Rajgarh','MP46 – Bhind','MP51 – Mandla','MP52 – Dindori'],
 'Maharashtra'=>['MH01 – Mumbai (South)','MH02 – Mumbai (West)','MH03 – Mumbai (East)','MH04 – Thane','MH05 – Kalyan','MH06 – Pen (Raigad)','MH07 – Sindhudurg','MH08 – Ratnagiri','MH09 – Kolhapur','MH10 – Sangli','MH11 – Satara','MH12 – Pune','MH13 – Solapur','MH14 – Pimpri-Chinchwad','MH15 – Nashik','MH16 – Ahmednagar','MH17 – Shrirampur','MH18 – Dhule','MH19 – Jalgaon','MH20 – Aurangabad (Chhatrapati Sambhajinagar)','MH21 – Jalna','MH22 – Parbhani','MH23 – Beed','MH24 – Latur','MH25 – Osmanabad (Dharashiv)','MH26 – Nanded','MH27 – Amravati','MH28 – Buldhana','MH29 – Yavatmal','MH30 – Akola','MH31 – Nagpur','MH32 – Wardha','MH33 – Gadchiroli','MH34 – Chandrapur','MH35 – Gondia','MH36 – Bhandara','MH37 – Washim','MH38 – Hingoli','MH39 – Nandurbar','MH41 – Malegaon (Nashik)','MH42 – Baramati (Pune)','MH43 – Navi Mumbai / Vashi','MH46 – Panvel (Raigad)','MH47 – Mumbai North / Borivali','MH48 – Vasai-Virar (Palghar)','MH49 – Nagpur (East)','MH50 – Karad (Satara)','MH53 – Pune (South)','MH54 – Pune (North)'],
 'Manipur'=>['MN01 – Imphal West','MN02 – Churachandpur','MN03 – Kangpokpi (Senapati)','MN04 – Thoubal','MN05 – Bishnupur','MN06 – Imphal East','MN07 – Ukhrul'],
 'Meghalaya'=>['ML01 – Shillong / East Khasi Hills','ML04 – Jaintia Hills (Jowai)','ML05 – East Khasi Hills (Shillong)','ML06 – West Khasi Hills (Nongstoin)','ML07 – East Garo Hills (Williamnagar)','ML08 – West Garo Hills (Tura)','ML09 – South Garo Hills (Baghmara)','ML10 – Ri-Bhoi (Nongpoh)','ML11 – East Jaintia Hills (Khliehriat)','ML12 – South-West Khasi Hills','ML13 – North Garo Hills (Resubelpara)','ML14 – South-West Garo Hills (Ampati)','ML15 – Eastern West Khasi Hills (Mairang)'],
 'Mizoram'=>['MZ01 – Aizawl','MZ02 – Lunglei','MZ03 – Saiha','MZ04 – Champhai','MZ05 – Kolasib','MZ06 – Serchhip','MZ07 – Lawngtlai','MZ08 – Mamit','MZ09 – Aizawl Rural'],
 'Nagaland'=>['NL01 – Kohima','NL02 – Mokokchung','NL03 – Tuensang','NL04 – Mon','NL05 – Wokha','NL06 – Zunheboto','NL07 – Dimapur','NL08 – Phek','NL10 – Kohima (Govt. non-transport)','NL11 – Kohima (Govt. transport)'],
 'Odisha (Orissa)'=>['OD01 – Balasore','OD02 – Bhubaneswar (Khordha)','OD03 – Bolangir','OD04 – Chandikhol (Jajpur)','OD05 – Cuttack','OD06 – Dhenkanal','OD07 – Ganjam / Berhampur','OD08 – Kalahandi (Bhawanipatna)','OD09 – Keonjhar','OD10 – Koraput','OD11 – Mayurbhanj (Baripada)','OD12 – Phulbani / Kandhamal','OD13 – Puri','OD14 – Rourkela (Sundergarh)','OD15 – Sambalpur','OD16 – Bargarh','OD17 – Jharsuguda','OD18 – Rayagada','OD19 – Angul','OD20 – Jajpur','OD21 – Bhadrak','OD22 – Nabarangpur','OD23 – Kendrapara','OD24 – Nayagarh','OD25 – Gajapati (Paralakhemundi)','OD27 – Khurda','OD28 – Nuapada','OD29 – Sonepur','OD30 – Boudh'],
 'Punjab'=>['PB02 – Amritsar','PB03 – Bathinda','PB04 – Faridkot','PB05 – Ferozepur (Firozpur)','PB06 – Gurdaspur','PB07 – Hoshiarpur','PB08 – Jalandhar','PB09 – Kapurthala','PB10 – Ludhiana','PB11 – Patiala','PB12 – Ropar / Rupnagar','PB13 – Sangrur','PB14 – Ajnala (Amritsar area)','PB15 – Abohar (Fazilka)','PB18 – Batala (Gurdaspur)','PB21 – Jagraon / Ludhiana sub-office','PB37 – Jalandhar (additional)','PB45 – Bathinda (additional)','PB91 – Ludhiana (additional)'],
 'Rajasthan'=>['RJ01 – Ajmer','RJ02 – Alwar','RJ03 – Banswara','RJ04 – Barmer','RJ05 – Bharatpur','RJ06 – Bhilwara','RJ07 – Bikaner','RJ08 – Bundi','RJ09 – Chittorgarh','RJ10 – Churu','RJ11 – Dholpur','RJ12 – Dungarpur','RJ13 – Ganganagar (Sri Ganganagar)','RJ14 – Jaipur','RJ15 – Jaisalmer','RJ16 – Jalore','RJ17 – Jhalawar','RJ18 – Jhunjhunu','RJ19 – Jodhpur','RJ20 – Karauli','RJ21 – Kota','RJ22 – Nagaur','RJ23 – Pali','RJ24 – Rajsamand','RJ25 – Sirohi','RJ26 – Sikar','RJ27 – Tonk','RJ28 – Udaipur'],
 'Sikkim'=>['SK01 – Gangtok (East Sikkim)','SK02 – Gyalshing (West Sikkim)','SK03 – Mangan (North Sikkim)','SK04 – Namchi (South Sikkim)','SK05 – Soreng (West Sikkim)','SK06 – Gangtok (additional)','SK07 – State / special series','SK08 – Singtam (East Sikkim)'],
 'Tamil Nadu'=>['TN01 – Chennai (Central)','TN02 – Chennai (North-West)','TN03 – Chennai (North-East)','TN04 – Chennai (East)','TN05 – Chennai (North)','TN06 – Chennai (South-East)','TN07 – Chennai (South)','TN09 – Chengalpattu','TN10 – Kancheepuram','TN11 – Tiruvallur','TN16 – Avadi','TN19 – Tiruvannamalai','TN20 – Vellore','TN21 – Arakkonam (Ranipet)','TN24 – Tirupattur','TN25 – Kallakurichi','TN26 – Cuddalore','TN27 – Villupuram','TN28 – Salem','TN29 – Erode','TN30 – Namakkal','TN31 – Tiruchirappalli (Trichy)','TN32 – Karur','TN33 – Perambalur','TN34 – Ariyalur','TN35 – Pudukkottai','TN36 – Madurai (Central)','TN37 – Theni','TN38 – Dindigul','TN39 – Tiruppur (North)','TN40 – Mettupalayam','TN41 – Pollachi','TN42 – Tiruppur (South)','TN43 – Coimbatore (Central)','TN44 – Coimbatore (North)','TN45 – Coimbatore (South)','TN51 – Nilgiris (Ooty)','TN52 – Kanyakumari','TN53 – Nagercoil','TN54 – Ramanathapuram','TN55 – Sivaganga','TN57 – Virudhunagar','TN58 – Thoothukudi / Tuticorin','TN60 – Tirunelveli','TN61 – Tenkasi','TN77 – Chengalpattu (sub-RTO)'],
 'Telangana'=>['TS01 – Adilabad','TS02 – Karimnagar','TS03 – Mahbubnagar','TS04 – Khammam','TS05 – Nalgonda','TS06 – Nizamabad','TS07 – Warangal','TS08 – Hyderabad (Central)','TS09 – Hyderabad (Zone-2)','TS10 – Hyderabad (Zone-3)','TS11 – Ranga Reddy / Hyderabad outskirts','TS12 – Medak','TS13 – Rangareddy','TS14 – Sangareddy','TS15 – Siddipet','TS16 – Kamareddy','TS17 – Vikarabad','TS20 – Mahabubabad','TS21 – Jagtial','TS22 – Peddapalli','TS23 – Khammam (additional)','TS24 – Bhongir / Yadadri Bhuvanagiri','TS30 – Nirmal','TS33 – Gadwal (Jogulamba Gadwal)','TS35 – Mulugu'],
 'Tripura'=>['TR01 – Agartala (Central)','TR02 – Agartala (additional)','TR03 – Kailasahar / North Tripura','TR04 – Dhalai (Ambassa)','TR05 – Khowai','TR06 – Sepahijala (Udaipur)','TR07 – South Tripura / Sabroom','TR08 – Gomati / Udaipur','TR09 – West Tripura (Kamalpur)','TR10 – Unakoti'],
 'Uttar Pradesh'=>['UP11 – Saharanpur','UP12 – Muzaffarnagar','UP13 – Bulandshahr','UP14 – Ghaziabad','UP15 – Meerut','UP16 – Gautam Buddh Nagar (Noida)','UP17 – Baghpat','UP19 – Shamli','UP20 – Bijnor','UP21 – Moradabad','UP22 – Rampur','UP23 – Amroha','UP24 – Budaun','UP25 – Bareilly','UP26 – Pilibhit','UP27 – Shahjahanpur','UP30 – Hardoi','UP31 – Lakhimpur Kheri','UP32 – Lucknow','UP33 – Raebareli','UP34 – Sitapur','UP35 – Unnao','UP36 – Amethi','UP37 – Hapur','UP38 – Sambhal','UP40 – Bahraich','UP41 – Barabanki','UP42 – Ayodhya','UP43 – Gonda','UP44 – Sultanpur','UP45 – Akbarpur (Ambedkar Nagar)','UP46 – Balrampur','UP50 – Azamgarh','UP51 – Basti','UP52 – Deoria','UP53 – Gorakhpur','UP54 – Mau','UP55 – Siddharthnagar','UP56 – Maharajganj','UP58 – Kushinagar','UP60 – Ballia','UP61 – Ghazipur','UP62 – Chandauli','UP63 – Mirzapur','UP64 – Bhadohi (Sant Ravidas Nagar)','UP65 – Varanasi','UP66 – Jaunpur','UP67 – Prayagraj (Allahabad)','UP68 – Kaushambi','UP69 – Fatehpur','UP70 – Pratapgarh','UP71 – Kanpur Dehat','UP72 – Kanpur Nagar','UP73 – Etawah','UP74 – Farrukhabad','UP75 – Kannauj','UP76 – Auraiya','UP77 – Agra','UP78 – Firozabad','UP79 – Mainpuri','UP80 – Aligarh','UP81 – Mathura','UP82 – Hathras','UP83 – Etah','UP84 – Kasganj','UP85 – Jhansi','UP86 – Lalitpur','UP87 – Jalaun','UP88 – Hamirpur','UP89 – Mahoba','UP90 – Banda','UP91 – Chitrakoot','UP94 – Sonbhadra','UP95 – Shravasti','UP99 – Lucknow (temp. / special)'],
 'Uttarakhand'=>['UK01 – Almora','UK02 – Bageshwar','UK03 – Champawat','UK04 – Nainital','UK05 – Pithoragarh','UK06 – Udham Singh Nagar','UK07 – Dehradun','UK08 – Haridwar','UK09 – Tehri','UK10 – Uttarkashi','UK11 – Chamoli','UK12 – Pauri','UK13 – Rudraprayag','UK14 – Rishikesh','UK15 – Roorkee','UK16 – Kashipur'],
 'West Bengal'=>['WB01 – Kolkata (Beltala / Central)','WB02 – Kolkata (Beltala 4-wheelers)','WB03 – Kolkata (commercial / goods)','WB06 – Kolkata (Kasba)','WB07 – Kolkata (Salt Lake)','WB09 – Kolkata (Alipore / central)','WB11 – Barasat','WB12 – Howrah','WB16 – Hooghly (Chinsurah)','WB19 – Alipore','WB20 – South 24 Parganas','WB21 – Basirhat','WB23 – Barrackpore','WB27 – Bangaon','WB29 – Tamluk','WB31 – Contai / Kanthi','WB33 – Midnapore (Paschim)','WB37 – Bankura','WB38 – Purulia','WB39 – Bardhaman / Burdwan','WB41 – Asansol','WB43 – Bolpur (Birbhum)','WB44 – Suri (Birbhum)','WB45 – Malda','WB46 – Raiganj (Uttar Dinajpur)','WB47 – Siliguri','WB49 – Cooch Behar','WB50 – Alipurduar','WB51 – Murshidabad','WB52 – Krishnanagar (Nadia)','WB53 – Ranaghat (Nadia)'],
 'Andaman and Nicobar Islands'=>['AN01 – Port Blair (South Andaman)','AN02 – Car Nicobar','AN03 – Nancowry (Nicobar)','AN04 – Mayabunder (North & Middle Andaman)','AN05 – Diglipur'],
 'Chandigarh'=>['CH01 – Chandigarh (Central Office / Sector 17)','CH02 – Chandigarh (Additional / Industrial Area)'],
 'Dadra and Nagar Haveli and Daman and Diu'=>['DD01 – Daman','DD02 – Diu','DN09 – Silvassa (Dadra and Nagar Haveli)'],
 'Delhi (National Capital Territory of Delhi)'=>['DL01 – Mall Road, North Delhi (Model Town, Civil Lines, etc.)','DL02 – Tilak Marg, Central Delhi (Connaught Place, Darya Ganj, etc.)','DL03 – Sheikh Sarai, South Delhi (Saket, Mehrauli, etc.)','DL04 – Janakpuri, West Delhi (Vikaspuri, Rajouri Garden, etc.)','DL05 – Loni Road, North East Delhi (Seelampur, Shahdara, etc.)','DL06 – Sarai Kale Khan, South East Delhi (Lajpat Nagar, Okhla, etc.)','DL07 – Mayur Vihar, East Delhi (Preet Vihar, Patparganj, etc.)','DL08 – Wazirpur, North West Delhi (Ashok Vihar, Shalimar Bagh, etc.)','DL09 – Dwarka, South West Delhi (Najafgarh, Palam, etc.)','DL10 – Raja Garden, West Delhi-II (Punjabi Bagh, Paschim Vihar, etc.)','DL11 – Rohini, North West Delhi-II (Rohini, Pitampura, Mangolpuri, etc.)','DL12 – Vasant Vihar, South Delhi-II (Vasant Kunj, Chanakyapuri, RK Puram, etc.)','DL13 – Surajmal Vihar, East Delhi-II (Vivek Vihar, Anand Vihar, etc.)'],
 'Jammu and Kashmir'=>['JK01 – Srinagar','JK02 – Jammu','JK03 – Anantnag','JK04 – Budgam','JK05 – Baramulla','JK06 – Doda','JK07 – Kargil (Ladakh region)','JK08 – Kathua','JK09 – Kupwara','JK10 – Leh (Ladakh region)','JK11 – Pulwama','JK12 – Udhampur','JK13 – Poonch','JK14 – Rajouri','JK15 – Bandipora','JK16 – Ganderbal','JK17 – Kulgam','JK18 – Ramban','JK19 – Reasi','JK20 – Samba','JK21 – Shopian'],
 'Ladakh'=>['LA01 – Leh','LA02 – Kargil'],
 'Lakshadweep'=>['LD01 – Kavaratti (Lakshadweep HQ)','LD02 – Amini Island','LD03 – Andrott Island','LD04 – Minicoy Island','LD05 – Agatti Island'],
 'Puducherry'=>['PY01 – Puducherry (Urban)','PY02 – Karaikal','PY03 – Mahe','PY04 – Yanam','PY05 – Villianur (sub-office)','PY06 – Bahour (sub-office)'],
];
