<?php
namespace NAS\Core;
if ( ! defined( 'ABSPATH' ) ) exit;

/**
 * Custom Database layer — no WP_Query for business logic.
 * Optimized SQL only. Supports prepared statements, transactions, pagination.
 */
class Database {

    private static ?Database $instance = null;
    private static int $query_count    = 0;

    // TRACE: instance() — Called internally or via AJAX action.
    //        Steps: returns JSON error response on failure.
    //        Output: mixed result value.
    //        Edge cases: invalid input → error returned.
    public static function instance(): Database {
        if ( ! self::$instance ) self::$instance = new self();
        return self::$instance;
    }

    // TRACE: prefix() — Called internally or via AJAX action.
    //        Steps: returns JSON error response on failure.
    //        Output: mixed result value.
    //        Edge cases: empty input values handled.
    public function prefix( string $table ): string {
        global $wpdb;
        return $wpdb->prefix . 'nas_' . $table;
    }

    /** Shorthand alias for prefix() — used throughout the codebase */
    // TRACE: t() — Called internally or via AJAX action.
    //        Steps: returns JSON error response on failure.
    //        Output: mixed result value.
    //        Edge cases: empty input values handled.
    public function t( string $table ): string {
        return $this->prefix( $table );
    }

    /** Execute a prepared SELECT and return all rows */
    // TRACE: select() — Called internally or via AJAX action.
    //        Steps: returns JSON error response on failure.
    //        Output: mixed result value.
    //        Edge cases: empty input values handled.
    public function select( string $sql, $params = [], string $output = ARRAY_A ): array {
        global $wpdb;
        self::$query_count++;
        if ( ! is_array( $params ) ) $params = [ $params ];
        if ( ! empty( $params ) ) $sql = $wpdb->prepare( $sql, ...$params );
        return $wpdb->get_results( $sql, $output ) ?: [];
    }

    /** Return single row — supports ARRAY_A (default), ARRAY_N, or OBJECT output formats */
    // TRACE: row() — Called internally or via AJAX action.
    //        Steps: returns JSON error response on failure.
    //        Output: mixed result value.
    //        Edge cases: empty input values handled.
    public function row( string $sql, $params = [], string $output = ARRAY_A ) {
        global $wpdb;
        self::$query_count++;
        if ( ! is_array( $params ) ) $params = [ $params ];
        if ( ! empty( $params ) ) $sql = $wpdb->prepare( $sql, ...$params );
        return $wpdb->get_row( $sql, $output ) ?: null; // returns array when ARRAY_A
    }

    /** Return single value */
    // TRACE: scalar() — Called internally or via AJAX action.
    //        Steps: returns JSON error response on failure.
    //        Output: mixed result value.
    //        Edge cases: empty input values handled.
    public function scalar( string $sql, $params = [] ) {
        global $wpdb;
        self::$query_count++;
        if ( ! is_array( $params ) ) $params = [ $params ];
        if ( ! empty( $params ) ) $sql = $wpdb->prepare( $sql, ...$params );
        return $wpdb->get_var( $sql );
    }

    /** Return single column as flat array */
    // TRACE: column() — Called internally or via AJAX action.
    //        Steps: inserts DB row → returns JSON error response on failure.
    //        Output: mixed result value.
    //        Edge cases: empty input values handled.
    public function column( string $sql, $params = [], int $col_offset = 0 ): array {
        global $wpdb;
        self::$query_count++;
        if ( ! is_array( $params ) ) $params = [ $params ];
        if ( ! empty( $params ) ) $sql = $wpdb->prepare( $sql, ...$params );
        return $wpdb->get_col( $sql, $col_offset ) ?: [];
    }

    /** Insert row, return insert ID */
    // TRACE: insert() — Called internally or via AJAX action.
    //        Steps: inserts DB row → returns JSON error response on failure.
    //        Output: typed scalar value.
    //        Edge cases: invalid input → error returned.
    public function insert( string $table, array $data, array $formats = [] ): int {
        global $wpdb;
        self::$query_count++;
        $result = $wpdb->insert( $table, $data, $formats ?: null );
        return $result ? (int) $wpdb->insert_id : 0;
    }

    /**
     * Return the auto-increment ID generated by the last INSERT.
     * Called in 10+ places throughout the codebase — centralised here
     * so callers don't need to touch $wpdb directly.
     */
    // TRACE: last_insert_id() — Called internally or via AJAX action.
    //        Steps: updates DB row → returns JSON error response on failure.
    //        Output: typed scalar value.
    //        Edge cases: invalid input → error returned.
    public function last_insert_id(): int {
        global $wpdb;
        return (int) $wpdb->insert_id;
    }

    /**
     * Proxy to $wpdb->prepare() — several modules call $db->prepare() expecting
     * a prepared-statement helper. Delegates to the underlying wpdb instance.
     */
    // TRACE: prepare() — Called internally or via AJAX action.
    //        Steps: updates DB row → deletes DB row → returns JSON error response on failure.
    //        Output: typed scalar value.
    //        Edge cases: invalid input → error returned.
    public function prepare( string $sql, ...$args ): string {
        global $wpdb;
        return $wpdb->prepare( $sql, ...$args );
    }

    /** Update rows, return rows affected */
    // TRACE: update() — Called internally or via AJAX action.
    //        Steps: updates DB row → deletes DB row → returns JSON error response on failure.
    //        Output: typed scalar value.
    //        Edge cases: explicit false check on DB op.
    public function update( string $table, array $data, array $where, array $data_fmt = [], array $where_fmt = [] ): int {
        global $wpdb;
        self::$query_count++;
        return (int) $wpdb->update( $table, $data, $where, $data_fmt ?: null, $where_fmt ?: null );
    }

    /** Delete rows, return rows affected */
    // TRACE: delete() — Called internally or via AJAX action.
    //        Steps: deletes DB row → returns JSON error response on failure.
    //        Output: typed scalar value.
    //        Edge cases: explicit false check on DB op.
    public function delete( string $table, array $where, array $formats = [] ): int {
        global $wpdb;
        self::$query_count++;
        return (int) $wpdb->delete( $table, $where, $formats ?: null );
    }

    /** Execute raw query (migrations, complex SQL) */
    // TRACE: query() — Called internally or via AJAX action.
    //        Steps: returns JSON error response on failure.
    //        Output: mixed result value.
    //        Edge cases: explicit false check on DB op.
    public function query( string $sql ): bool {
        global $wpdb;
        self::$query_count++;
        return $wpdb->query( $sql ) !== false;
    }

    /** Transaction support */
    // TRACE: begin() — Called internally or via AJAX action.
    //        Steps: runs DB transaction → returns JSON error response on failure.
    //        Output: success/error JSON response.
    //        Edge cases: invalid input → error returned.
    public function begin(): void {
        global $wpdb;
        $wpdb->query( 'START TRANSACTION' );
    }

    // TRACE: commit() — Called internally or via AJAX action.
    //        Steps: runs DB transaction → returns JSON error response on failure.
    //        Output: success/error JSON response.
    //        Edge cases: invalid input → error returned.
    public function commit(): void {
        global $wpdb;
        $wpdb->query( 'COMMIT' );
    }

    // TRACE: rollback() — Called internally or via AJAX action.
    //        Steps: runs DB transaction → returns JSON error response on failure.
    //        Output: success/error JSON response.
    //        Edge cases: returns null/false on failure.
    public function rollback(): void {
        global $wpdb;
        $wpdb->query( 'ROLLBACK' );
    }

    /** Run callable in a transaction, auto-rollback on exception */
    // TRACE: transaction() — Called internally or via AJAX action.
    //        Steps: returns JSON error response on failure.
    //        Output: success/error JSON response.
    //        Edge cases: returns null/false on failure.
    public function transaction( callable $fn ): bool {
        $this->begin();
        try {
            $fn( $this );
            $this->commit();
            return true;
        } catch ( \Throwable $e ) {
            $this->rollback();
            if ( Config::instance()->is_dev() ) {
                error_log( 'NAS DB Transaction failed: ' . $e->getMessage() );
            }
            return false;
        }
    }

    /**
     * Paginated query — returns ['data'=>[], 'total'=>int, 'pages'=>int, 'page'=>int, 'per_page'=>int]
     *
     * Can be called two ways:
     *   paginate( $count_sql, $data_sql, $params, $page, $per_page )  — explicit count query
     *   paginate( $data_sql, $params, $page, $per_page )              — count auto-wrapped
     */
    // TRACE: paginate() — Called internally or via AJAX action.
    //        Steps: queries DB.
    //        Output: scalar value (int/float/string) from DB.
    //        Edge cases: invalid input → error returned.
    public function paginate(): array {
        global $wpdb;
        $args = func_get_args();

        if ( count( $args ) === 5 ) {
            // 5-arg form: count_sql, data_sql, params, page, per_page
            [ $count_sql, $data_sql, $params, $page, $per_page ] = $args;
        } else {
            // 4-arg form: data_sql, params, page, per_page — auto-generate count
            [ $data_sql, $params, $page, $per_page ] = $args;
            // Strip ORDER BY for count subquery
            $stripped   = preg_replace( '/\s+ORDER\s+BY\s+.+$/is', '', $data_sql );
            $count_sql  = "SELECT COUNT(*) FROM ( $stripped ) AS _nas_count_wrap";
        }

        $page      = max( 1, (int) $page );
        $per_page  = max( 1, (int) $per_page );
        $offset    = ( $page - 1 ) * $per_page;
        $total     = (int) $this->scalar( $count_sql, (array) $params );
        $paginated = $data_sql . $wpdb->prepare( ' LIMIT %d OFFSET %d', $per_page, $offset );
        $data      = $this->select( $paginated, (array) $params );

        return [
            'data'     => $data,
            'bookings' => $data,   // alias — some callers use 'bookings' key
            'items'    => $data,   // alias — some callers use 'items' key
            'total'    => $total,
            'pages'    => $per_page > 0 ? (int) ceil( $total / $per_page ) : 1,
            'page'     => $page,
            'per_page' => $per_page,
        ];
    }

    /** Get last error */
    // TRACE: last_error() — Called internally or via AJAX action.
    //        Steps: returns JSON error response on failure.
    //        Output: mixed result value.
    //        Edge cases: invalid input → error returned.
    public function last_error(): string {
        global $wpdb;
        return $wpdb->last_error ?: '';
    }

    // TRACE: query_count() — Called internally or via AJAX action.
    //        Steps: returns JSON error response on failure.
    //        Output: mixed result value.
    //        Edge cases: invalid input → error returned.
    public static function query_count(): int {
        return self::$query_count;
    }

    /** Escape LIKE values */
    // TRACE: esc_like() — Called internally or via AJAX action.
    //        Steps: returns JSON error response on failure.
    //        Output: mixed result value.
    //        Edge cases: invalid input → error returned.
    public function esc_like( string $val ): string {
        global $wpdb;
        return $wpdb->esc_like( $val );
    }

    /** Quick helper: table exists? */
    // TRACE: table_exists() — Called internally or via AJAX action.
    //        Steps: returns JSON error response on failure.
    //        Output: mixed result value.
    //        Edge cases: invalid input → error returned.
    public function table_exists( string $table ): bool {
        global $wpdb;
        return (bool) $wpdb->get_var( $wpdb->prepare( 'SHOW TABLES LIKE %s', $table ) );
    }

    /** Return raw wpdb instance */
    // TRACE: raw() — Called internally or via AJAX action.
    //        Steps: executes operation.
    //        Output: mixed result value.
    //        Edge cases: invalid input → error returned.
    public function raw(): \wpdb {
        global $wpdb;
        return $wpdb;
    }


}
